local M = {}

function M.gen()
    local set_hl = function(group, opts)
        vim.api.nvim_set_hl(0, group, opts)
    end
    local colors = require("eink.palette")

    local c = {
        bg = colors.bg,
        bg1 = colors.gray1,
        bg2 = colors.gray2,
        bg3 = colors.gray3,
        bg4 = colors.gray4,
        fg = colors.fg,
        fg1 = colors.fg,
        fg2 = colors.subfg,
        fg3 = colors.subfg,
        fg4 = colors.subbg,
        gray = colors.subfg,
        red = colors.red,
        green = colors.green,
        yellow = colors.yellow,
        blue = colors.blue,
        purple = colors.purple,
        cyan = colors.cyan,
        orange = colors.yellow,
        
        bright_red = colors.bright_red,
        bright_green = colors.bright_green,
        bright_yellow = colors.bright_yellow,
        bright_blue = colors.bright_blue,
        bright_purple = colors.bright_purple,
        bright_cyan = colors.bright_cyan,
    }

    local groups = {
        -- Base
        Normal = { fg = c.fg, bg = c.bg },
        NormalFloat = { fg = c.fg, bg = c.bg },
        NormalNC = { link = "Normal" },
        CursorLine = { bg = c.bg1 },
        CursorColumn = { link = "CursorLine" },
        TabLineFill = { fg = c.fg4, bg = c.bg1 },
        TabLineSel = { fg = c.green, bg = c.bg1 },
        TabLine = { link = "TabLineFill" },
        MatchParen = { bg = c.bg3, bold = true },
        ColorColumn = { bg = c.bg1 },
        Conceal = { fg = c.blue },
        CursorLineNr = { fg = c.yellow, bg = c.bg1 },
        NonText = { fg = c.bg2 },
        SpecialKey = { fg = c.fg4 },
        Visual = { bg = c.bg3 }, -- Selection
        VisualNOS = { link = "Visual" },
        Search = { fg = c.yellow, bg = c.bg, reverse = true },
        IncSearch = { fg = c.orange, bg = c.bg, reverse = true },
        CurSearch = { link = "IncSearch" },
        QuickFixLine = { fg = c.purple },
        Underlined = { fg = c.blue, underline = true },
        StatusLine = { fg = c.fg, bg = c.bg2, bold = true },
        StatusLineNC = { fg = c.fg4, bg = c.bg1 },
        WinBar = { fg = c.fg4, bg = c.bg },
        WinBarNC = { fg = c.fg3, bg = c.bg1 },
        WinSeparator = { fg = c.bg3, bg = c.bg },
        WildMenu = { fg = c.blue, bg = c.bg2, bold = true },
        Directory = { fg = c.green, bold = true },
        Title = { fg = c.green, bold = true },
        ErrorMsg = { fg = c.bg, bg = c.red, bold = true },
        MoreMsg = { fg = c.yellow, bold = true },
        ModeMsg = { link = "MoreMsg" },
        Question = { fg = c.orange, bold = true },
        WarningMsg = { fg = c.red, bold = true },
        LineNr = { fg = c.bg4 },
        SignColumn = { bg = c.bg },
        Folded = { fg = c.gray, bg = c.bg1, italic = true },
        FoldColumn = { fg = c.gray, bg = c.bg1 },
        Cursor = { reverse = true },
        vCursor = { link = "Cursor" },
        iCursor = { link = "Cursor" },
        lCursor = { link = "Cursor" },
        Special = { fg = c.orange },
        Comment = { fg = c.gray, italic = true },
        Todo = { fg = c.bg, bg = c.yellow, bold = true, italic = true },
        Done = { fg = c.orange, bold = true, italic = true },
        Error = { fg = c.red, bold = true },
        
        -- Standard Syntax
        Statement = { fg = c.red },
        Conditional = { link = "Statement" },
        Repeat = { link = "Statement" },
        Label = { link = "Statement" },
        Exception = { link = "Statement" },
        Operator = { fg = c.orange, italic = true },
        Keyword = { link = "Statement" },
        Identifier = { fg = c.blue },
        Function = { fg = c.green, bold = true },
        PreProc = { fg = c.cyan },
        Include = { link = "PreProc" },
        Define = { link = "PreProc" },
        Macro = { link = "PreProc" },
        PreCondit = { link = "PreProc" },
        Constant = { fg = c.purple },
        Character = { link = "Constant" },
        String = { fg = c.green, italic = true },
        Boolean = { link = "Constant" },
        Number = { link = "Constant" },
        Float = { link = "Constant" },
        Type = { fg = c.yellow },
        StorageClass = { fg = c.orange },
        Structure = { fg = c.cyan },
        Typedef = { fg = c.yellow },
        
        -- PMenu
        Pmenu = { fg = c.fg, bg = c.bg2 },
        PmenuSel = { fg = c.bg2, bg = c.blue, bold = true },
        PmenuSbar = { bg = c.bg2 },
        PmenuThumb = { bg = c.bg4 },
        
        -- Diff
        DiffDelete = { bg = c.bright_red },
        DiffAdd = { bg = c.bright_green },
        DiffChange = { bg = c.bright_blue },
        DiffText = { bg = c.yellow, fg = c.bg },

        -- Spell
        SpellCap = { sp = c.blue, underline = true },
        SpellBad = { sp = c.red, underline = true },
        SpellLocal = { sp = c.cyan, underline = true },
        SpellRare = { sp = c.purple, underline = true },
        
        -- Whitespace
        Whitespace = { fg = c.bg2 },
        Delimiter = { fg = c.orange },
        EndOfBuffer = { link = "NonText" },

        -- Diagnostics
        DiagnosticError = { fg = c.red },
        DiagnosticWarn = { fg = c.yellow },
        DiagnosticInfo = { fg = c.blue },
        DiagnosticHint = { fg = c.cyan },
        DiagnosticOk = { fg = c.green },
        DiagnosticSignError = { fg = c.red, bg = c.bg },
        DiagnosticSignWarn = { fg = c.yellow, bg = c.bg },
        DiagnosticSignInfo = { fg = c.blue, bg = c.bg },
        DiagnosticSignHint = { fg = c.cyan, bg = c.bg },
        DiagnosticSignOk = { fg = c.green, bg = c.bg },
        DiagnosticUnderlineError = { sp = c.red, underline = true },
        DiagnosticUnderlineWarn = { sp = c.yellow, underline = true },
        DiagnosticUnderlineInfo = { sp = c.blue, underline = true },
        DiagnosticUnderlineHint = { sp = c.cyan, underline = true },
        DiagnosticUnderlineOk = { sp = c.green, underline = true },
        
        -- LSP References
        LspReferenceRead = { fg = c.yellow, bold = true },
        LspReferenceTarget = { link = "Visual" },
        LspReferenceText = { fg = c.yellow, bold = true },
        LspReferenceWrite = { fg = c.orange, bold = true },
        LspCodeLens = { fg = c.gray },
        LspSignatureActiveParameter = { link = "Search" },

        -- Git
        gitcommitSelectedFile = { fg = c.green },
        gitcommitDiscardedFile = { fg = c.red },
        GitSignsAdd = { fg = c.green },
        GitSignsChange = { fg = c.orange },
        GitSignsDelete = { fg = c.red },

        -- NvimTree
        NvimTreeSymlink = { fg = c.cyan },
        NvimTreeRootFolder = { fg = c.purple, bold = true },
        NvimTreeFolderIcon = { fg = c.blue, bold = true },
        NvimTreeFileIcon = { fg = c.fg2 },
        NvimTreeExecFile = { fg = c.green, bold = true },
        NvimTreeOpenedFile = { fg = c.bright_red, bold = true },
        NvimTreeSpecialFile = { fg = c.yellow, bold = true, underline = true },
        NvimTreeImageFile = { fg = c.purple },
        NvimTreeIndentMarker = { fg = c.bg3 },
        NvimTreeGitDirty = { fg = c.yellow },
        NvimTreeGitStaged = { fg = c.yellow },
        NvimTreeGitMerge = { fg = c.purple },
        NvimTreeGitRenamed = { fg = c.purple },
        NvimTreeGitNew = { fg = c.yellow },
        NvimTreeGitDeleted = { fg = c.red },
        NvimTreeWindowPicker = { bg = c.cyan },

        -- Debug
        debugPC = { link = "DiffAdd" },
        debugBreakpoint = { link = "DiagnosticSignError" },

        -- Telescope
        TelescopeNormal = { fg = c.fg, bg = c.bg },
        TelescopeSelection = { link = "CursorLine" },
        TelescopeSelectionCaret = { fg = c.red },
        TelescopeMultiSelection = { fg = c.gray },
        TelescopeBorder = { link = "TelescopeNormal" },
        TelescopePromptBorder = { link = "TelescopeNormal" },
        TelescopeResultsBorder = { link = "TelescopeNormal" },
        TelescopePreviewBorder = { link = "TelescopeNormal" },
        TelescopeMatching = { fg = c.orange },
        TelescopePromptPrefix = { fg = c.red },
        TelescopePrompt = { link = "TelescopeNormal" },

        -- Cmp
        CmpItemAbbr = { fg = c.fg },
        CmpItemAbbrDeprecated = { fg = c.fg, strikethrough = true },
        CmpItemAbbrMatch = { fg = c.blue, bold = true },
        CmpItemAbbrMatchFuzzy = { fg = c.blue, underline = true },
        CmpItemMenu = { fg = c.gray },
        CmpItemKindText = { fg = c.orange },
        CmpItemKindVariable = { fg = c.orange },
        CmpItemKindMethod = { fg = c.blue },
        CmpItemKindFunction = { fg = c.blue },
        CmpItemKindConstructor = { fg = c.yellow },
        CmpItemKindUnit = { fg = c.blue },
        CmpItemKindField = { fg = c.blue },
        CmpItemKindClass = { fg = c.yellow },
        CmpItemKindInterface = { fg = c.yellow },
        CmpItemKindModule = { fg = c.blue },
        CmpItemKindProperty = { fg = c.blue },
        CmpItemKindValue = { fg = c.orange },
        CmpItemKindEnum = { fg = c.yellow },
        CmpItemKindOperator = { fg = c.yellow },
        CmpItemKindKeyword = { fg = c.purple },
        CmpItemKindEvent = { fg = c.purple },
        CmpItemKindReference = { fg = c.purple },
        CmpItemKindColor = { fg = c.purple },
        CmpItemKindSnippet = { fg = c.green },
        CmpItemKindFile = { fg = c.blue },
        CmpItemKindFolder = { fg = c.blue },
        CmpItemKindEnumMember = { fg = c.cyan },
        CmpItemKindConstant = { fg = c.orange },
        CmpItemKindStruct = { fg = c.yellow },
        CmpItemKindTypeParameter = { fg = c.yellow },

        -- HTML/XML
        htmlTag = { fg = c.cyan, bold = true },
        htmlEndTag = { fg = c.cyan, bold = true },
        htmlTagName = { fg = c.blue },
        htmlArg = { fg = c.orange },
        htmlTagN = { fg = c.fg },
        htmlSpecialTagName = { fg = c.blue },
        htmlLink = { fg = c.subbg, underline = true },
        xmlTag = { fg = c.cyan, bold = true },
        xmlEndTag = { fg = c.cyan, bold = true },
        xmlTagName = { fg = c.blue },
        xmlAttrib = { fg = c.orange },
        
        -- Markdown
        markdownH1 = { fg = c.green, bold = true },
        markdownH2 = { fg = c.green, bold = true },
        markdownH3 = { fg = c.yellow, bold = true },
        markdownH4 = { fg = c.yellow, bold = true },
        markdownH5 = { fg = c.yellow },
        markdownH6 = { fg = c.yellow },
        markdownCode = { fg = c.cyan },
        markdownCodeBlock = { fg = c.cyan },
        markdownCodeDelimiter = { fg = c.cyan },
        markdownBlockquote = { fg = c.gray },
        markdownListMarker = { fg = c.gray },
        markdownUrl = { fg = c.purple },
        markdownLinkText = { fg = c.gray, underline = true },

        -- Treesitter
        ["@comment"] = { link = "Comment" },
        ["@none"] = { bg = "NONE", fg = "NONE" },
        ["@preproc"] = { link = "PreProc" },
        ["@define"] = { link = "Define" },
        ["@operator"] = { link = "Operator" },
        ["@punctuation.delimiter"] = { link = "Delimiter" },
        ["@punctuation.bracket"] = { link = "Delimiter" },
        ["@punctuation.special"] = { link = "Delimiter" },
        ["@string"] = { link = "String" },
        ["@string.regex"] = { link = "String" },
        ["@string.escape"] = { link = "SpecialChar" },
        ["@string.special"] = { link = "SpecialChar" },
        ["@string.special.path"] = { link = "Underlined" },
        ["@string.special.symbol"] = { link = "Identifier" },
        ["@string.special.url"] = { link = "Underlined" },
        ["@character"] = { link = "Character" },
        ["@character.special"] = { link = "SpecialChar" },
        ["@boolean"] = { link = "Boolean" },
        ["@number"] = { link = "Number" },
        ["@float"] = { link = "Float" },
        ["@function"] = { link = "Function" },
        ["@function.builtin"] = { link = "Special" },
        ["@function.call"] = { link = "Function" },
        ["@function.macro"] = { link = "Macro" },
        ["@function.method"] = { link = "Function" },
        ["@method"] = { link = "Function" },
        ["@method.call"] = { link = "Function" },
        ["@constructor"] = { link = "Special" },
        ["@parameter"] = { link = "Identifier" },
        ["@keyword"] = { link = "Keyword" },
        ["@keyword.conditional"] = { link = "Conditional" },
        ["@keyword.debug"] = { link = "Debug" },
        ["@keyword.directive"] = { link = "PreProc" },
        ["@keyword.directive.define"] = { link = "Define" },
        ["@keyword.exception"] = { link = "Exception" },
        ["@keyword.function"] = { link = "Keyword" },
        ["@keyword.import"] = { link = "Include" },
        ["@keyword.operator"] = { link = "Operator" },
        ["@keyword.repeat"] = { link = "Repeat" },
        ["@keyword.return"] = { link = "Keyword" },
        ["@keyword.storage"] = { link = "StorageClass" },
        ["@conditional"] = { link = "Conditional" },
        ["@repeat"] = { link = "Repeat" },
        ["@label"] = { link = "Label" },
        ["@include"] = { link = "Include" },
        ["@exception"] = { link = "Exception" },
        ["@type"] = { link = "Type" },
        ["@type.builtin"] = { link = "Type" },
        ["@type.definition"] = { link = "Typedef" },
        ["@type.qualifier"] = { link = "Type" },
        ["@storageclass"] = { link = "StorageClass" },
        ["@attribute"] = { link = "PreProc" },
        ["@field"] = { link = "Identifier" },
        ["@property"] = { link = "Identifier" },
        ["@variable"] = { link = "Identifier" },
        ["@variable.builtin"] = { link = "Special" },
        ["@variable.member"] = { link = "Identifier" },
        ["@variable.parameter"] = { link = "Identifier" },
        ["@constant"] = { link = "Constant" },
        ["@constant.builtin"] = { link = "Special" },
        ["@constant.macro"] = { link = "Define" },
        ["@markup"] = { link = "Normal" },
        ["@markup.strong"] = { bold = true },
        ["@markup.italic"] = { italic = true },
        ["@markup.underline"] = { underline = true },
        ["@markup.heading"] = { link = "Title" },
        ["@markup.raw"] = { link = "String" },
        ["@markup.link"] = { link = "Underlined" },
        ["@markup.link.label"] = { link = "SpecialChar" },
        ["@markup.list"] = { link = "Delimiter" },
        ["@markup.list.checked"] = { fg = c.green },
        ["@markup.list.unchecked"] = { fg = c.gray },
        ["@diff.plus"] = { link = "DiffAdd" },
        ["@diff.minus"] = { link = "DiffDelete" },
        ["@diff.delta"] = { link = "DiffChange" },
        ["@module"] = { link = "Normal" },
        ["@namespace"] = { link = "Normal" },
        ["@symbol"] = { link = "Identifier" },
        ["@text"] = { link = "Normal" },
        ["@text.strong"] = { bold = true },
        ["@text.emphasis"] = { italic = true },
        ["@text.underline"] = { underline = true },
        ["@text.title"] = { link = "Title" },
        ["@text.uri"] = { link = "Underlined" },
        ["@tag"] = { link = "Tag" },
        ["@tag.attribute"] = { link = "Identifier" },
        ["@tag.delimiter"] = { link = "Delimiter" },

        -- LSP Semantics
        ["@lsp.type.class"] = { link = "@type" },
        ["@lsp.type.comment"] = { link = "@comment" },
        ["@lsp.type.decorator"] = { link = "@macro" },
        ["@lsp.type.enum"] = { link = "@type" },
        ["@lsp.type.enumMember"] = { link = "@constant" },
        ["@lsp.type.function"] = { link = "@function" },
        ["@lsp.type.interface"] = { link = "@constructor" },
        ["@lsp.type.macro"] = { link = "@macro" },
        ["@lsp.type.method"] = { link = "@method" },
        ["@lsp.type.namespace"] = { link = "@namespace" },
        ["@lsp.type.parameter"] = { link = "@parameter" },
        ["@lsp.type.property"] = { link = "@property" },
        ["@lsp.type.struct"] = { link = "@type" },
        ["@lsp.type.type"] = { link = "@type" },
        ["@lsp.type.typeParameter"] = { link = "@type.definition" },
        ["@lsp.type.variable"] = { link = "@variable" },

        -- Mini
        MiniCompletionActiveParameter = { underline = true },
        MiniCursorword = { underline = true },
        MiniCursorwordCurrent = { underline = true },
        MiniDiffSignAdd = { fg = c.green },
        MiniDiffSignChange = { fg = c.cyan },
        MiniDiffSignDelete = { fg = c.red },
        MiniFilesFile = { fg = c.fg },
        MiniFilesTitle = { fg = c.green, bold = true },
        MiniFilesTitleFocused = { fg = c.orange, bold = true },
        MiniIconsBlue = { fg = c.blue },
        MiniIconsCyan = { fg = c.cyan },
        MiniIconsGreen = { fg = c.green },
        MiniIconsOrange = { fg = c.orange },
        MiniIconsPurple = { fg = c.purple },
        MiniIconsRed = { fg = c.red },
        MiniIconsYellow = { fg = c.yellow },
        MiniIndentscopeSymbol = { fg = c.gray },
        MiniIndentscopeSymbolOff = { fg = c.yellow },
        MiniJump = { fg = c.orange, underline = true },
        MiniPickBorder = { link = "FloatBorder" },
        MiniPickMatchCurrent = { bg = c.bg2 },
        MiniPickMatchMarked = { link = "Visual" },
        MiniPickNormal = { link = "NormalFloat" },
        MiniStarterCurrent = { nocombine = true },
        MiniStarterFooter = { fg = c.gray },
        MiniStarterHeader = { link = "Title" },
        MiniStarterInactive = { link = "Comment" },
        MiniStarterItem = { link = "Normal" },
        MiniStarterItemBullet = { link = "Delimiter" },
        MiniStarterItemPrefix = { link = "WarningMsg" },
        MiniStarterSection = { link = "Delimiter" },
        MiniStarterQuery = { link = "MoreMsg" },
        MiniStatuslineDevinfo = { link = "StatusLine" },
        MiniStatuslineFileinfo = { link = "StatusLine" },
        MiniStatuslineFilename = { link = "StatusLineNC" },
        MiniStatuslineInactive = { link = "StatusLineNC" },
        MiniStatuslineModeCommand = { fg = c.bg, bg = c.yellow, bold = true },
        MiniStatuslineModeInsert = { fg = c.bg, bg = c.blue, bold = true },
        MiniStatuslineModeNormal = { fg = c.bg, bg = c.fg, bold = true },
        MiniStatuslineModeOther = { fg = c.bg, bg = c.cyan, bold = true },
        MiniStatuslineModeReplace = { fg = c.bg, bg = c.red, bold = true },
        MiniStatuslineModeVisual = { fg = c.bg, bg = c.green, bold = true },
        MiniTablineCurrent = { fg = c.green, bg = c.bg1, bold = true },
        MiniTablineFill = { link = "TabLineFill" },
        MiniTablineHidden = { fg = c.bg4, bg = c.bg1 },
        MiniTablineModifiedCurrent = { fg = c.bg1, bg = c.green, bold = true },
        MiniTablineModifiedHidden = { fg = c.bg1, bg = c.bg4 },
        MiniTablineModifiedVisible = { fg = c.bg1, bg = c.fg },
        MiniTablineVisible = { fg = c.fg, bg = c.bg1 },
        
        -- NeoTree
        NeoTreeDirectoryName = { fg = c.green, bold = true },
        NeoTreeFileName = { fg = c.fg },
        NeoTreeFileNameOpened = { fg = c.fg, bold = true },
        NeoTreeGitAdded = { fg = c.green },
        NeoTreeGitConflict = { fg = c.orange, bold = true },
        NeoTreeGitDeleted = { fg = c.red },
        NeoTreeGitModified = { fg = c.orange },
        NeoTreeGitUntracked = { fg = c.orange, italic = true },
        
        -- Notify
        NotifyERRORBorder = { fg = c.red },
        NotifyERRORIcon = { fg = c.red },
        NotifyERRORTitle = { fg = c.red },
        NotifyINFOBorder = { fg = c.cyan },
        NotifyINFOIcon = { fg = c.cyan },
        NotifyINFOTitle = { fg = c.cyan },
        NotifyWARNBorder = { fg = c.yellow },
        NotifyWARNIcon = { fg = c.yellow },
        NotifyWARNTitle = { fg = c.yellow },

        -- Dashboard
        DashboardHeader = { fg = c.cyan },
        DashboardCenter = { fg = c.yellow },
        DashboardFooter = { fg = c.purple, italic = true },
    }

    for group, opts in pairs(groups) do
        set_hl(group, opts)
    end
end

return M
